name: monopoly_banking
description: A cloud-based monopoly banking app.
publish_to: 'none'

version: 0.6.0+9

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  fleasy: ^0.5.0
  flutter_bloc: ^7.2.0
  flutter_hooks: ^0.18.0
  kt_dart: ^0.9.1
  url_strategy: ^0.2.0
  font_awesome_flutter: ^9.1.0
  currency_text_input_formatter: ^2.1.2
  modal_bottom_sheet: ^2.0.0
  confetti: ^0.6.0-nullsafety
  flutter_signin_button: ^2.0.0
  package_info_plus: ^1.0.6
  url_launcher: ^6.0.10
  share_plus: ^2.1.4

  user_repository:
    path: packages/user_repository
  banking_repository:
    path: packages/banking_repository

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#303030"

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"