name: monopoly_banking
description: A cloud-based monopoly banking app.
publish_to: 'none'

version: 0.2.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  fleasy: ^0.5.0
  flutter_bloc: ^7.1.0
  flutter_hooks: ^0.18.0
  firebase_auth: ^3.0.1
  kt_dart: ^0.9.1
  url_strategy: ^0.2.0
  font_awesome_flutter: ^9.1.0
  currency_text_input_formatter: ^2.1.2
  modal_bottom_sheet: ^2.0.0

  auth_repository:
    path: packages/auth_repository
  banking_repository:
    path: packages/banking_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true