name: monopoly_banking
description: A cloud-based monopoly banking app.
publish_to: 'none'

version: 0.2.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  fleasy: ^0.5.0
  flutter_bloc: ^7.1.0
  flutter_hooks: ^0.18.0
  kt_dart: ^0.9.1
  url_strategy: ^0.2.0
  font_awesome_flutter: ^9.1.0
  currency_text_input_formatter: ^2.1.2
  modal_bottom_sheet: ^2.0.0
  flutter_native_splash: ^1.2.1

  user_repository:
    path: packages/user_repository
  banking_repository:
    path: packages/banking_repository
  shared:
    path: packages/shared

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#0175C2"