name: banking_repository
description: Package which manages the banking logic and data.
version: 1.0.0

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fleasy: ^0.6.0
  firebase_core: ^1.7.0
  cloud_firestore: ^2.5.3
  equatable: ^2.0.3
  kt_dart: ^0.9.1
  deep_pick: ^0.9.0
  ntp: ^2.0.0

  user_repository:
    path: ../user_repository

  shared:
    path: ../shared